import React from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";

interface ReceiptDetailModalProps {
  isOpen: boolean;
  onClose: () => void;
  receipt: any | null;
}

const ReceiptDetailModal = ({ isOpen, onClose, receipt }: ReceiptDetailModalProps) => {
  if (!receipt) return null;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-lg max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Receipt Details</DialogTitle>
          <DialogDescription>
            Detailed information for receipt number: <strong>{receipt.receipt_number}</strong>
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4 mt-4">
          <div><strong>Date:</strong> {new Date(receipt.date).toLocaleDateString()}</div>
          <div><strong>Book Number:</strong> {receipt.book_number}</div>
          <div><strong>Trader Name:</strong> {receipt.trader_name}</div>
          <div><strong>Trader Address:</strong> {receipt.trader_address}</div>
          <div><strong>Payee Name:</strong> {receipt.payee_name}</div>
          <div><strong>Payee Address:</strong> {receipt.payee_address}</div>
          <div><strong>Commodity:</strong> {receipt.commodity}</div>
          <div><strong>Quantity:</strong> {receipt.quantity} {receipt.unit}</div>
          <div><strong>Value:</strong> ₹{Number(receipt.value).toLocaleString()}</div>
          <div><strong>Nature of Receipt:</strong> {receipt.nature_of_receipt}</div>
          <div><strong>Fees Paid:</strong> ₹{receipt.fees_paid}</div>
          <div><strong>Vehicle Number:</strong> {receipt.vehicle_number}</div>
          <div><strong>Invoice Number:</strong> {receipt.invoice_number}</div>
          <div><strong>Collection Location:</strong> {receipt.collection_location}</div>
          <div><strong>Collected By:</strong> {receipt.collected_by}</div>
          <div><strong>Checkpost Location:</strong> {receipt.checkpost_location}</div>
          <div><strong>Generated By:</strong> {receipt.generated_by}</div>
          <div><strong>Designation:</strong> {receipt.designation}</div>
          <div><strong>Status:</strong> {receipt.status}</div>
        </div>
        <DialogFooter>
          <Button onClick={onClose}>Close</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default ReceiptDetailModal;
