// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tttouxvtexzhwzxwuvtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0dG91eHZ0ZXh6aHd6eHd1dnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDE0NDQsImV4cCI6MjA2NTQ3NzQ0NH0.hZ2Jn30DuYGUsbq0w0gdnV6-iEAY1l9ym4t87uZTORY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);